version: '3.9'
services:
  app:
    image: node:18.16.0-alpine3.16
    volumes:
      - ./:/project
    command: tail -f /dev/null
    ports:
      - "3002:3000"
      - "24678:24678"
  backend:
    image: node:18.16.0-alpine3.16
    volumes:
      - ./:/project
    command: tail -f /dev/null
    ports:
      - "8080:8000"
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
      - ./configdb:/data/configdb
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo