version: '3.9'
services:
  app:
    image: node:18.16.0-alpine3.16
    volumes:
      - ./:/project
    command: tail -f /dev/null
    ports:
      - "3002:3000"
      - "24678:24678"
  backend:
    image: node:18.16.0-alpine3.16
    volumes:
      - ./:/project
    command: tail -f /dev/null
    ports:
      - "8080:8000"